### ISSUE TITLE
Crash on !addctf

### ISSUE THREAD

**Issue by Corb3nik** [OpenToAllCTF/OTA-Challenge-Bot#41]
Used the command `!addctf tw2017`.

Which produced the following error message : 
```
2017-09-01 14:39:29,675 - botserver            - Received bot command : addctf tw2017 (C0JQ9NVAA)
2017-09-01 14:39:29,675 - handler_factory      - Processing message: addctf tw2017 from C0JQ9NVAA (U1EUDSN5S)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/src/server/botserver.py", line 164, in run
    self.slack_client.rtm_read())
  File "/src/server/botserver.py", line 116, in parseSlackMessage
    return (output['text'][1:].strip().lower(), output['channel'], output['user'])
KeyError: 'user'
```

**Comment by Grazfather** [comment]
The parser wasn't filtering on `message` type, so you probably got some weird thing that had a text field but wasn't a message. Fixed in 4abbcbaa0c9ef491061e21868e683283f64997a4
