### ISSUE TITLE
OTA bot crashes

### ISSUE THREAD

**Issue by Corb3nik** [OpenToAllCTF/OTA-Challenge-Bot#73]
OTA bot crashed for some reason.

I have not investigated yet, so here is the error trace : 

```
2017-12-12 18:43:25,524 - botserver            - Web socket error. Executing reconnect...
Traceback (most recent call last):
  File "/home/otabot/code/OTA-Challenge-Bot/server/botserver.py", line 118, in run
    message = self.slack_wrapper.read()
  File "/home/otabot/code/OTA-Challenge-Bot/util/slack_wrapper.py", line 28, in read
    return self.client.rtm_read()
  File "/home/otabot/code/OTA-Challenge-Bot/venv/lib/python3.5/site-packages/slackclient/client.py", line 128, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/home/otabot/code/OTA-Challenge-Bot/venv/lib/python3.5/site-packages/slackclient/server.py", line 186, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/home/otabot/code/OTA-Challenge-Bot/venv/lib/python3.5/site-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/home/otabot/code/OTA-Challenge-Bot/venv/lib/python3.5/site-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/otabot/code/OTA-Challenge-Bot/venv/lib/python3.5/site-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/home/otabot/code/OTA-Challenge-Bot/venv/lib/python3.5/site-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/otabot/code/OTA-Challenge-Bot/venv/lib/python3.5/site-packages/websocket/_abnf.py", line 340, in recv_frame
    self.recv_header()
  File "/home/otabot/code/OTA-Challenge-Bot/venv/lib/python3.5/site-packages/websocket/_abnf.py", line 288, in recv_header
    header = self.recv_strict(2)
  File "/home/otabot/code/OTA-Challenge-Bot/venv/lib/python3.5/site-packages/websocket/_abnf.py", line 375, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/otabot/code/OTA-Challenge-Bot/venv/lib/python3.5/site-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/home/otabot/code/OTA-Challenge-Bot/venv/lib/python3.5/site-packages/websocket/_socket.py", line 93, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
2017-12-12 18:43:25,677 - botserver            - Connection failed. Invalid slack token or bot id?
2017-12-12 18:43:25,677 - botserver            - Shutdown complete...
2017-12-12 18:43:25,678 - consolethread        - Shutting down
2017-12-12 18:43:25,678 - run                  - Server has shut down. Quit
```

**Comment by Grazfather** [comment]
Looks like it's just because we were running master before merging in kileak's changes from development. See #74

**Comment by Kileak** [comment]
Not sure on this one, since the log from corb already shows the message from the exception handler.

It seems that the bot failed on doing the reconnect, since it goes into the else branch after the check, if it has connected successfully. 

Maybe we should a sleep in the error handler, so it doesn't reconnect immediately. Maybe the slack api was blocking us there.

**Comment by Kileak** [comment]
Is this still happening or are we good on that one?

**Comment by Corb3nik** [comment]
Let's keep it open until after Codegate CTF 2018 Preliminary, if it doesn't crash, let's close this.
